export {Contact} from './contacts'
export {Footer} from './footer'
export {Header} from './header'
export {Jobs} from 'components/jobs'
export {Main} from './main'
export {Skills} from 'components/skills'