export {SvgIconReact} from './SvgIconReact'
export {SvgIconRedux} from './SvgIconRedux'
export {SvgIconTypeScript} from './SvgIconTypeScript'
export {SvgIconJavaScript} from './SvgIconJavaScript'
export {SvgIconHtml} from './SvgIconHtml'
export {SvgIconCss} from './SvgIconCss'
export {SvgIconGit} from './SvgIconGit'
export {SvgIconGitHub} from './SvgIconGitHub'
export {SvgIconMaterialUi} from './SvgIconMaterialUi'
export {SvgIconStoryBook} from './SvgIconStoryBook'
export {SvgIconUnitTest} from './SvgIconUnitTest'
export {SvgIconResponsiveDesign } from './SvgIconResponsiveDesign'
export {SvgIconTelegram} from './SvgIconTelegram'
export {SvgIconWhatsApp} from './SvgIconWhatsApp'
export {SvgIconLinkedIn} from './SvgIconLinkedIn'
export {SvgIconPhone} from './SvgIconPhone'
export {SvgIconDownload} from './SvgIconDownload'